GET https://www.omdbapi.com/?apikey=23887cb6&s=nightmare HTTP/1.1

###

GET https://www.omdbapi.com/?apikey=23887cb6&s=nightmare&page=1 HTTP/1.1

###

GET https://www.omdbapi.com/?apikey=23887cb6&s=terminator&type=game HTTP/1.1

###

GET https://www.omdbapi.com/?apikey=23887cb6&

###

GET https://www.omdbapi.com/?apikey=23887cb6&i=tt0103064

###

GET https://www.omdbapi.com/?apikey=23887cb6&s=terminator&type=series HTTP/1.1

###